Add platform specific icons
pariyatti/mobile-app pull request #32
Opened 2020-08-15 18:22 UTC by VarunBarad

Closes #24

2020-08-19 08:39 UTC, deobald requested changes
On the whole, this is 100x better than the old approach. I suggested adding a few tests around the behaviour.

2020-08-19 08:39 UTC, deobald commented on lib/ui/common_widgets/pariyatti_icons.dart
> +  static IconData get(IconName name) {
Since this method is now doing all the heavy lifting, I'd actually suggest we wrap it in a few unit tests. One happy path (`'ios'`, since `'default'` it a special case) + "what happens when the OS isn't there?" + "what happens for the explicit default case?"

In that third test, I assume Android explicitly returns `'default'` for `Platform.operatingSystem`? If not, we should actually make Android a happy path (`icons.containsKey(Platform.operatingSystem)` should return `true`) because treating Android as a default is okay, but not through the fallback path in the conditional, since future code edits are very likely to make assumptions about what `icons.containsKey(Platform.operatingSystem) == false` means.

2020-08-19 08:39 UTC, deobald commented on lib/ui/common_widgets/pariyatti_icons.dart
> +  static IconData get(IconName name) {
Hope this all makes sense. If not, grab me for a chat. :)

2020-08-19 17:05 UTC, VarunBarad commented on lib/ui/common_widgets/pariyatti_icons.dart
> +  static IconData get(IconName name) {
No platform is explicitly going to return `'default'` for `Platform.operatingSystem`, so the third test case cannot exist. I agree with making Android first-class as far as icons are considered instead of it getting its icons from fallback.

Now when we are discussing testing and I am writing things down, I am realizing that I don't know how to write test cases which would take different paths for different platforms and then **make** them take those paths; I don't control value provided by `Platform.operatingSystem` therefore I cannot test different cases returned by `Platform.operatingSystem` in the way that the code is currently structured.

If I wanted to test this method that way then I would have to be passing platform name to the `get` method. But that would increase one extra parameter at every calling site for this function. What do you think we should do?

2020-08-20 07:31 UTC, deobald commented on lib/ui/common_widgets/pariyatti_icons.dart
> +  static IconData get(IconName name) {
> No platform is explicitly going to return 'default' for Platform.operatingSystem, so the third test case cannot exist.

Sorry, I wasn't sure what Android returned for `Platform.operatingSystem` so my comment was a little too flexible. Let me try that again:

1. `P.oS` returns `'ios'` and takes that path
2. `P.oS` returns `'android'` (or whatever) and explicitly takes a happy path based on that. There's no good way to assert the happy path was taken without mucking up the implementation but the fact an Android-specific test exists tells the reader that this isn't just "the default path" even without reading the implementation to see that for a fact.
3. `P.oS` returns `'fuscia'` (or whatever... something real, though) to trigger the default path.

> What do you think we should do?

The weird-and-probably-still-valid way to do this for many years has been to _wrap_ `Platform`. This actually has advantages in your implementation: You can then inject behaviour or add "aspects" to it without any weird reflection magic or (god forbid, in the languages which permit this) re-opening the actual `Platform` class and changing its behaviour _internally_ (barf).

The wrapper won't do much in practice... and may never do much. But "wrap all native types" is an old Java rule that still comes in handy and in this particular case wrapping `Platform` with a `PariyattiPlatform` (or maybe something less verbose?) will give you a way to take control of the class in the test.

Alternatively, there are probably mocking frameworks available for Dart. In general, I prefer wrapping to mocking. But this one I'll leave up to you as the Dart/Flutter expert. :)

2021-11-20 21:41 UTC, deobald commented
I think this change is okay as-is to go into the mainline so we can (a) move the project to the org root in GitHub and (b) make `master` the trunk branch. We should still add tests at some point.

2021-11-20 21:41 UTC, merged