replace AppBar with CollapsibleSliverApp bars ✨
pariyatti/mobile-app pull request #39
Opened 2020-08-16 13:13 UTC by Prathik-Jain

fixes #33

2020-08-19 17:24 UTC, VarunBarad commented
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-08-19 at 22 50 02](https://user-images.githubusercontent.com/8678857/90668934-6e1e9780-e26e-11ea-9180-31af6bdffa5f.png)

I feel like the space at the top is way too big, can we decrease that somehow?

2020-08-19 17:33 UTC, VarunBarad requested changes
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-08-19 at 22 50 02](https://user-images.githubusercontent.com/8678857/90668934-6e1e9780-e26e-11ea-9180-31af6bdffa5f.png)

I feel like the space at the top is way too big, can we decrease that somehow?

2020-08-19 17:33 UTC, VarunBarad commented on lib/ui/common_widgets/slivered_view.dart
> +        headerSliverBuilder: (_, __) {
Question: I thought we could specify both parameters as `_`, do we need to specify separate names like done here?

2020-08-20 16:58 UTC, Prathik-Jain commented on lib/ui/common_widgets/slivered_view.dart
> +        headerSliverBuilder: (_, __) {
yes, we get a `Error: Duplicated parameter name '_'` otherwise.

2020-08-20 17:01 UTC, Prathik-Jain commented on lib/ui/common_widgets/slivered_view.dart
> +              expandedHeight: 120,
@VarunBarad mind changing the `expandedHeight` to whatever you think suits the best?

2020-08-20 17:20 UTC, deobald commented on lib/ui/common_widgets/slivered_view.dart
> +              expandedHeight: 120,
try to match wireframes, plox & thx. <3

2021-10-31 01:01 UTC, deobald commented on lib/ui/common_widgets/slivered_view.dart
> +              expandedHeight: 120,
I'll adjust this after the PR is merged (if I can get it merged).

2021-10-31 01:03 UTC, merged