API wrapper added, image loaded callback added to cached image package
pariyatti/mobile-app pull request #54
Opened 2021-02-25 08:52 UTC by NamanShergill

2021-02-26 23:41 UTC, deobald reviewed
I don't think it has to happen in this same PR, but it would be great to rip out the old SQL caching layer. It looks like the Dio stuff is much simpler and, assuming everything works as it should, we shouldn't keep the old code lying around.

2021-02-27 01:28 UTC, deobald commented
Sorry for making a mess of the PR history... got confused by "convert to draft". Anyway.

We should move the custom `flutter_cached_network_image` code to https://github.com/pariyatti/flutter_cached_network_image and use that as the dependency instead of including the code in this repo. Once that change is done we can merge this PR if someone (other than me and @NamanShergill) has had a look at the code. <3

2021-03-10 19:32 UTC, VarunBarad requested changes
@deobald @NamanShergill I have left a few suggestions on the code, but they are mostly just formatting and a single code-quality improvement.

The changes at this point are now mostly above my understanding level.

2021-03-10 19:32 UTC, VarunBarad commented on lib/api/api.dart
> +    final todayUrl = '/api/v1/today.json';
If we don't need the attributes `_database` and `_client` we should remove them.

2021-03-10 19:32 UTC, VarunBarad commented on lib/app/cache.dart
> +          maxStale: Duration(days: 7), forceRefresh: refresh);
```suggestion
  static Options images({bool refresh = true}) => buildCacheOptions(
        Duration(seconds: 15),
        maxStale: Duration(days: 7),
        forceRefresh: refresh,
      );
```

Formatting suggestion

2021-03-10 19:32 UTC, VarunBarad commented on lib/app/cache.dart
> +          maxStale: Duration(days: 7), forceRefresh: refresh);
```suggestion
  static Options todayCards({bool refresh = true}) => buildCacheOptions(
        Duration(seconds: 15),
        maxStale: Duration(days: 7),
        forceRefresh: refresh,
      );
```

Formatting suggestion

2021-03-10 19:32 UTC, VarunBarad commented on lib/ui/common_widgets/cards/OverlayInspirationCard.dart
> +import '../../../util.dart';
We should not mix `package:patta/...` and file-path imports, I remember being bitten by Flutter/Dart not recognizing the appropriate types.

It would be strongly advised to instead import `import 'package:patta/util.dart';` here

2021-03-13 19:23 UTC, deobald commented
Merging this. @NamanShergill can apply @VarunBarad 's suggestions after. I'll make the fix to `import '../../../util.dart';`.

2021-03-13 19:24 UTC, merged